// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication.API.Models.Northwind;

[Table("employee_territories", Schema = "public")]
public partial class EmployeeTerritory
{
    [Key]
    [Column("employee_id")]
    public int EmployeeId { get; set; }
    [Key]
    [Column("territory_id")]
    [StringLength(20)]
    public string TerritoryId { get; set; }

    [ForeignKey(nameof(EmployeeId))]
    [InverseProperty("EmployeeTerritories")]
    public virtual Employee Employee { get; set; }
    [ForeignKey(nameof(TerritoryId))]
    [InverseProperty("EmployeeTerritories")]
    public virtual Territory Territory { get; set; }
}
