// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication.API.Models.Northwind;

[Table("order_details", Schema = "public")]
public partial class OrderDetail
{
    [Key]
    [Column("order_id")]
    public int OrderId { get; set; }
    [Key]
    [Column("product_id")]
    public int ProductId { get; set; }
    [Column("unit_price")]
    public float UnitPrice { get; set; }
    [Column("quantity")]
    public short Quantity { get; set; }
    [Column("discount")]
    public float Discount { get; set; }

    [ForeignKey(nameof(OrderId))]
    [InverseProperty("OrderDetails")]
    public virtual Order Order { get; set; }
    [ForeignKey(nameof(ProductId))]
    [InverseProperty("OrderDetails")]
    public virtual Product Product { get; set; }
}
