// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication.API.Models.Northwind;

[Table("orders", Schema = "public")]
public partial class Order
{
    public Order()
    {
        OrderDetails = new HashSet<OrderDetail>();
    }

    [Key]
    [Column("order_id")]
    public int OrderId { get; set; }
    [Column("customer_id")]
    [StringLength(5)]
    public string CustomerId { get; set; }
    [Column("employee_id")]
    public int? EmployeeId { get; set; }
    [Column("order_date")]
    public DateTime? OrderDate { get; set; }
    [Column("required_date")]
    public DateTime? RequiredDate { get; set; }
    [Column("shipped_date")]
    public DateTime? ShippedDate { get; set; }
    [Column("ship_via")]
    public int? ShipVia { get; set; }
    [Column("freight")]
    public float? Freight { get; set; }
    [Column("ship_name")]
    [StringLength(40)]
    public string ShipName { get; set; }
    [Column("ship_address")]
    [StringLength(60)]
    public string ShipAddress { get; set; }
    [Column("ship_city")]
    [StringLength(15)]
    public string ShipCity { get; set; }
    [Column("ship_region")]
    [StringLength(15)]
    public string ShipRegion { get; set; }
    [Column("ship_postal_code")]
    [StringLength(10)]
    public string ShipPostalCode { get; set; }
    [Column("ship_country")]
    [StringLength(15)]
    public string ShipCountry { get; set; }

    [ForeignKey(nameof(CustomerId))]
    [InverseProperty("Orders")]
    public virtual Customer Customer { get; set; }
    [ForeignKey(nameof(EmployeeId))]
    [InverseProperty("Orders")]
    public virtual Employee Employee { get; set; }
    [ForeignKey(nameof(ShipVia))]
    [InverseProperty(nameof(Shipper.Orders))]
    public virtual Shipper ShipViaNavigation { get; set; }
    [InverseProperty(nameof(OrderDetail.Order))]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; }
}
