// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication.API.Models.Northwind;

[Table("products", Schema = "public")]
public partial class Product
{
    public Product()
    {
        OrderDetails = new HashSet<OrderDetail>();
    }

    [Key]
    [Column("product_id")]
    public int ProductId { get; set; }
    [Required]
    [Column("product_name")]
    [StringLength(40)]
    public string ProductName { get; set; }
    [Column("supplier_id")]
    public int? SupplierId { get; set; }
    [Column("category_id")]
    public int? CategoryId { get; set; }
    [Column("quantity_per_unit")]
    [StringLength(20)]
    public string QuantityPerUnit { get; set; }
    [Column("unit_price")]
    public float? UnitPrice { get; set; }
    [Column("units_in_stock")]
    public short? UnitsInStock { get; set; }
    [Column("units_on_order")]
    public short? UnitsOnOrder { get; set; }
    [Column("reorder_level")]
    public short? ReorderLevel { get; set; }
    [Required]
    [Column("discontinued")]
    public bool? Discontinued { get; set; }

    [ForeignKey(nameof(CategoryId))]
    [InverseProperty("Products")]
    public virtual Category Category { get; set; }
    [ForeignKey(nameof(SupplierId))]
    [InverseProperty("Products")]
    public virtual Supplier Supplier { get; set; }
    [InverseProperty(nameof(OrderDetail.Product))]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; }
}
