// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication.API.Models.Northwind;

[Table("suppliers", Schema = "public")]
public partial class Supplier
{
    public Supplier()
    {
        Products = new HashSet<Product>();
    }

    [Key]
    [Column("supplier_id")]
    public int SupplierId { get; set; }
    [Required]
    [Column("company_name")]
    [StringLength(40)]
    public string CompanyName { get; set; }
    [Column("contact_name")]
    [StringLength(30)]
    public string ContactName { get; set; }
    [Column("contact_title")]
    [StringLength(30)]
    public string ContactTitle { get; set; }
    [Column("address")]
    [StringLength(60)]
    public string Address { get; set; }
    [Column("city")]
    [StringLength(15)]
    public string City { get; set; }
    [Column("region")]
    [StringLength(15)]
    public string Region { get; set; }
    [Column("postal_code")]
    [StringLength(10)]
    public string PostalCode { get; set; }
    [Column("country")]
    [StringLength(15)]
    public string Country { get; set; }
    [Column("phone")]
    [StringLength(24)]
    public string Phone { get; set; }
    [Column("fax")]
    [StringLength(24)]
    public string Fax { get; set; }
    [Column("homepage")]
    public string HomePage { get; set; }

    [JsonIgnore]
    [InverseProperty(nameof(Product.Supplier))]
    public virtual ICollection<Product> Products { get; set; }
}
